// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQkeSI3iZCgZnDrq3zBpfKtFPWB2Ltthk',
    appId: '1:933756063979:web:cf948977b0b257f0bcaeae',
    messagingSenderId: '933756063979',
    projectId: 'authlearn-a0092',
    authDomain: 'authlearn-a0092.firebaseapp.com',
    storageBucket: 'authlearn-a0092.firebasestorage.app',
    measurementId: 'G-W14GBXMRYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx37sbvVgyyon6nLlVQTy-GqASGAwQINY',
    appId: '1:933756063979:android:4598b5f35362bcd8bcaeae',
    messagingSenderId: '933756063979',
    projectId: 'authlearn-a0092',
    storageBucket: 'authlearn-a0092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrbMoMzJ1jwoQ65G9C3UUxczcaK2nTY-o',
    appId: '1:933756063979:ios:29e6f4953a4ee555bcaeae',
    messagingSenderId: '933756063979',
    projectId: 'authlearn-a0092',
    storageBucket: 'authlearn-a0092.firebasestorage.app',
    iosBundleId: 'com.example.shopping1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrbMoMzJ1jwoQ65G9C3UUxczcaK2nTY-o',
    appId: '1:933756063979:ios:29e6f4953a4ee555bcaeae',
    messagingSenderId: '933756063979',
    projectId: 'authlearn-a0092',
    storageBucket: 'authlearn-a0092.firebasestorage.app',
    iosBundleId: 'com.example.shopping1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQkeSI3iZCgZnDrq3zBpfKtFPWB2Ltthk',
    appId: '1:933756063979:web:c970f50224428565bcaeae',
    messagingSenderId: '933756063979',
    projectId: 'authlearn-a0092',
    authDomain: 'authlearn-a0092.firebaseapp.com',
    storageBucket: 'authlearn-a0092.firebasestorage.app',
    measurementId: 'G-LP2654T2XC',
  );
}
